name: Google Indexing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  indexing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: robingenz/action-google-indexing@v1.0.0
        with:
          siteUrl: 'https://www.sgomberosicilia.it'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
